# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b0978045235e95b65bf07087b3c981a4f7dcb44a0415a00278ec5a63f4ec20c0d4ba224bb7dd41924b47cf1ea6634ac51c670a2788737500a2470b6ee48f960

test:
  secret_key_base: 5b12c1857218e093af01b818e30c0e4e814560549989330e547d565faac66772e75a489bd71e41f4e63ae1f3c69ef94acc6bc9832b4af34d734399f28d9db996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
